### ISSUE TITLE
Cant remove event listeners

### ISSUE THREAD

**Issue by Olian04** [Olian04/brynja#35]
Somehow this slipped past both the unit tests and half a year of production.

```js
const { render } = brynja;

render(_=>_
  .child('button', _=>_
  	.text('first render')
  	.on('click', () => {
    	console.log('first render');
    })
  )
);

render(_=>_
  .child('button', _=>_
  	.text('second render')
  	.on('click', () => {
    	console.log('second render');
    })
  )
);
```

Clicking the button will log both `first render` & `second render`.
However it should only log `second render`.

**Comment by Olian04** [comment]
Related to #22

**Comment by landeholt** [comment]
Have you considered to create a proxy for the events instead of removing the builtin ones?
